title: 'BitDevs @ The Bitcoin Learning Center | Bitcoin Chiang Mai, Thailand'
tagline: 'BitDevs is a regular community series for Bitcoiners interested in Bitcoin's latest research and technical development.'

menu:
  - {name: 'About', url: '/about'}
  - {name: 'Events', url: '/events'}
  - {name: 'Join', url: '/join'}
  - {name: 'Links', url: '/links'}
  - {name: 'Donate', url: '/donate'}
#  - {name: 'Blog', url: '/blog'}
# - {name: 'Meetup', url: 'https://www.meetup.com/BitDevsNYC/', external: true}
# - {name: 'Cities', url: '/cities'}
